#!/bin/sh -l
#FILENAME:  ongputest

#SBATCH -A canli-k
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --time=2:30:00
#SBATCH --job-name ongputest
#SBATCH --output=/home/chen4433/joboutput/ongputest/11.out

module load cuda
echo $CUDA_VISIBLE_DEVICE
module load conda
conda activate base

python main.py --dataset case14_ieee --cfg_idx 0

